
[pc,score,latent,tsquare] = princomp(Total_cell_normalized');

cumsum(latent)./sum(latent);

%biplot(pc(:,1:3),'Scores',score(:,1:3),'VarLabels',...
		%{'RMP','Input Resistance', 'Tau','Sag Ratio','Rheobase current','Firing rate at 200 pA',...
        %'Input output slope','Adaptation ratio','Fast-doublet ratio','AP width','AP AHP','AP amplitude','AP maximum depolarization rate','AP maximum repolarization rate'})
        
%biplot(pc(:,1:2),'Scores',score(:,1:2),'VarLabels',...
		%{'RMP','Input Resistance', 'Tau','Sag Ratio','Rheobase current','Firing rate at 200 pA',...
        %'Input output slope','AP theshold','AP width','AP AHP','AP amplitude', 'Onset Latency'})
    
biplot(pc(:,1:2),'Scores',score(:,1:2),'VarLabels',...
		{'Input Resistance', 'Tau','Firing rate at 200 pA',...
        'Input output slope','AP theshold','AP width','AP AHP','AP amplitude', 'Onset Latency'})